"""
Code Archaeologist - PDF Report Export
Week 3: Export analysis to PDF using reportlab
"""

import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        Image, PageBreak, ListFlowable, ListItem
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


class PDFReportGenerator:
    """
    Week 3: Generate PDF reports from code analysis
    
    Includes:
    - Call graph visualization
    - Query results
    - AI explanations
    - Statistics
    """
    
    def __init__(self, output_path: str):
        """
        Initialize PDF generator
        
        Args:
            output_path: Where to save the PDF
        """
        self.output_path = output_path
        self.styles = getSampleStyleSheet() if HAS_REPORTLAB else None
        
        if self.styles:
            # Custom styles
            self.styles.add(ParagraphStyle(
                'CodeStyle',
                parent=self.styles['Code'],
                fontSize=8,
                leftIndent=20
            ))
            self.styles.add(ParagraphStyle(
                'FunctionName',
                parent=self.styles['Heading3'],
                textColor=colors.blue
            ))
    
    def is_available(self) -> bool:
        """Check if reportlab is available"""
        return HAS_REPORTLAB
    
    def generate_report(
        self,
        project_name: str,
        graph_data: Dict[str, Any],
        query_results: Dict[str, Any],
        ai_explanations: Optional[List[Dict]] = None,
        graph_image_path: Optional[str] = None
    ) -> str:
        """
        Generate comprehensive PDF report
        
        Args:
            project_name: Name of the project analyzed
            graph_data: Graph statistics and info
            query_results: Results from various queries
            ai_explanations: AI function explanations
            graph_image_path: Path to graph visualization image
            
        Returns:
            Path to generated PDF
        """
        if not self.is_available():
            raise ImportError("reportlab required: pip install reportlab")
        
        doc = SimpleDocTemplate(
            self.output_path,
            pagesize=A4,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        story = []
        
        # Title Page
        story.extend(self._create_title_page(project_name))
        story.append(PageBreak())
        
        # Executive Summary
        story.extend(self._create_summary(graph_data))
        story.append(PageBreak())
        
        # Graph Visualization
        if graph_image_path and os.path.exists(graph_image_path):
            story.extend(self._create_graph_section(graph_image_path))
            story.append(PageBreak())
        
        # Query Results
        story.extend(self._create_query_results(query_results))
        story.append(PageBreak())
        
        # AI Explanations
        if ai_explanations:
            story.extend(self._create_ai_section(ai_explanations))
            story.append(PageBreak())
        
        # Function List
        story.extend(self._create_function_list(graph_data.get('functions', [])))
        
        # Footer
        story.append(Spacer(1, 0.5*inch))
        story.append(Paragraph(
            f"Generated by Code Archaeologist v3.0.0 | {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            self.styles['Normal']
        ))
        
        # Build PDF
        doc.build(story)
        
        return self.output_path
    
    def _create_title_page(self, project_name: str) -> List[Any]:
        """Create title page"""
        elements = []
        
        # Title
        elements.append(Spacer(1, 2*inch))
        elements.append(Paragraph(
            "Code Archaeologist",
            ParagraphStyle(
                'MainTitle',
                parent=self.styles['Heading1'],
                fontSize=28,
                alignment=TA_CENTER,
                textColor=colors.HexColor('#1f77b4')
            )
        ))
        
        elements.append(Spacer(1, 0.3*inch))
        elements.append(Paragraph(
            "Code Analysis Report",
            ParagraphStyle(
                'Subtitle',
                parent=self.styles['Heading2'],
                fontSize=18,
                alignment=TA_CENTER
            )
        ))
        
        elements.append(Spacer(1, 0.5*inch))
        elements.append(Paragraph(
            f"Project: {project_name}",
            self.styles['Heading2']
        ))
        
        elements.append(Spacer(1, 0.2*inch))
        elements.append(Paragraph(
            f"Date: {datetime.now().strftime('%B %d, %Y')}",
            self.styles['Normal']
        ))
        
        elements.append(Spacer(1, 0.5*inch))
        elements.append(Paragraph(
            "Week 3: Multi-language + AI + FastAPI",
            self.styles['Italic']
        ))
        
        return elements
    
    def _create_summary(self, graph_data: Dict) -> List[Any]:
        """Create executive summary section"""
        elements = []
        
        elements.append(Paragraph("Executive Summary", self.styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        # Check if batch analysis
        is_batch = graph_data.get('is_batch', False)
        files_analyzed = graph_data.get('files_analyzed', 1)
        
        # Stats table
        stats = [
            ['Metric', 'Value'],
        ]
        
        if is_batch:
            stats.append(['Files Analyzed', str(files_analyzed)])
            stats.append(['Batch Analysis', 'Yes'])
        
        stats.extend([
            ['Total Functions', str(graph_data.get('function_count', 0))],
            ['Call Graph Nodes', str(graph_data.get('node_count', 0))],
            ['Call Graph Edges', str(graph_data.get('edge_count', 0))],
            ['Total Events', str(graph_data.get('total_events', 0))],
            ['Languages Detected', ', '.join(graph_data.get('languages', ['Python']))],
            ['Processing Time', f"{graph_data.get('processing_time_ms', 0)} ms"],
        ])
        
        table = Table(stats, colWidths=[3*inch, 2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 14),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(table)
        elements.append(Spacer(1, 0.3*inch))
        
        # Description
        desc = """
        This report provides a comprehensive analysis of the codebase structure,
        including call graphs, dependency analysis, and AI-powered function
        explanations.
        """
        elements.append(Paragraph(desc, self.styles['Normal']))
        
        return elements
    
    def _create_graph_section(self, image_path: str) -> List[Any]:
        """Create graph visualization section"""
        elements = []
        
        elements.append(Paragraph("Call Graph Visualization", self.styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        # Add graph image
        img = Image(image_path, width=6*inch, height=4*inch)
        elements.append(img)
        
        elements.append(Spacer(1, 0.2*inch))
        elements.append(Paragraph(
            "Figure 1: Call graph showing function relationships",
            self.styles['Italic']
        ))
        
        return elements
    
    def _create_query_results(self, results: Dict) -> List[Any]:
        """Create query results section"""
        elements = []
        
        elements.append(Paragraph("Query Results", self.styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        for query_name, query_data in results.items():
            elements.append(Paragraph(
                query_name.replace('_', ' ').title(),
                self.styles['Heading2']
            ))
            
            if isinstance(query_data, list):
                for item in query_data[:20]:  # Limit to 20 items
                    elements.append(Paragraph(f"• {item}", self.styles['Normal']))
                if len(query_data) > 20:
                    elements.append(Paragraph(
                        f"... and {len(query_data) - 20} more",
                        self.styles['Italic']
                    ))
            else:
                elements.append(Paragraph(str(query_data), self.styles['Normal']))
            
            elements.append(Spacer(1, 0.1*inch))
        
        return elements
    
    def _create_ai_section(self, explanations: List[Dict]) -> List[Any]:
        """Create AI explanations section"""
        elements = []
        
        elements.append(Paragraph("AI-Powered Function Analysis", self.styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        elements.append(Paragraph(
            "The following functions were analyzed using GPT-3.5-Turbo:",
            self.styles['Normal']
        ))
        elements.append(Spacer(1, 0.2*inch))
        
        for i, exp in enumerate(explanations[:10], 1):  # Limit to 10
            func_name = exp.get('function_name', f'Function {i}')
            explanation = exp.get('explanation', 'No explanation available')
            
            elements.append(Paragraph(f"{i}. {func_name}", self.styles['FunctionName']))
            elements.append(Paragraph(explanation, self.styles['Normal']))
            
            # Key points
            key_points = exp.get('key_points', [])
            if key_points:
                elements.append(Paragraph("Key Points:", self.styles['Heading4']))
                for point in key_points:
                    elements.append(Paragraph(f"  • {point}", self.styles['Normal']))
            
            elements.append(Spacer(1, 0.15*inch))
        
        if len(explanations) > 10:
            elements.append(Paragraph(
                f"... and {len(explanations) - 10} more functions analyzed",
                self.styles['Italic']
            ))
        
        return elements
    
    def _create_function_list(self, functions: List[str]) -> List[Any]:
        """Create function list section"""
        elements = []
        
        elements.append(Paragraph("Complete Function List", self.styles['Heading1']))
        elements.append(Spacer(1, 0.2*inch))
        
        # Create multi-column list
        func_list = []
        for func in sorted(functions):
            func_list.append(f"• {func}")
        
        # Split into columns
        cols = 2
        rows = (len(func_list) + cols - 1) // cols
        
        table_data = []
        for i in range(rows):
            row = []
            for j in range(cols):
                idx = i + j * rows
                if idx < len(func_list):
                    row.append(func_list[idx])
                else:
                    row.append('')
            table_data.append(row)
        
        if table_data:
            table = Table(table_data, colWidths=[3*inch, 3*inch])
            table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Courier'),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            elements.append(table)
        
        return elements


def export_to_pdf(
    project_name: str,
    output_path: str,
    graph_data: Dict,
    query_results: Dict,
    ai_explanations: Optional[List[Dict]] = None
) -> str:
    """
    Quick export to PDF
    
    Usage:
        export_to_pdf("My Project", "report.pdf", graph_data, queries)
    """
    generator = PDFReportGenerator(output_path)
    return generator.generate_report(
        project_name=project_name,
        graph_data=graph_data,
        query_results=query_results,
        ai_explanations=ai_explanations
    )


if __name__ == '__main__':
    # Test
    print("PDF Report Generator - Week 3")
    print("=" * 50)
    
    if not HAS_REPORTLAB:
        print("⚠️ reportlab not installed: pip install reportlab")
    else:
        print("✅ reportlab available")
        
        # Create test report
        test_data = {
            'function_count': 5,
            'node_count': 10,
            'edge_count': 15,
            'languages': ['Python'],
            'functions': ['process', 'main', 'helper', 'init', 'cleanup']
        }
        
        test_queries = {
            'callers': ['main', 'process'],
            'dead_code': ['unused_func']
        }
        
        test_ai = [
            {
                'function_name': 'process',
                'explanation': 'Processes data and returns result',
                'key_points': ['Validates input', 'Transforms data']
            }
        ]
        
        try:
            path = export_to_pdf(
                "Test Project",
                "test_report.pdf",
                test_data,
                test_queries,
                test_ai
            )
            print(f"✅ Test report generated: {path}")
        except Exception as e:
            print(f"❌ Error: {e}")
